id: a4df6e5e467d47449fac4b2db97acec6
initial_creation_type: ocr
source_metadata:
  volumes:
    f4fa8683717d424b87576c89ab08397c:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: རྟེན་ཅིང་འབྲེལ་པར་འབྱུང་བའི་སྙིང་པོའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1605
      volume_number: 57
